# Generated by Django 2.2.4 on 2020-03-10 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('DepartmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerModel',
            fields=[
                ('managerID', models.IntegerField(primary_key=True, serialize=False)),
                ('managerName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('employeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=10)),
                ('employeeName', models.CharField(max_length=50)),
                ('departmentModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.DepartmentModel')),
                ('managerModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.ManagerModel')),
            ],
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='managerModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.ManagerModel'),
        ),
    ]
